<?php

define('CONSUMER_KEY', 'SFtcUBB5IImkmpff2ezVg');
define('CONSUMER_SECRET', 'MXMSnSTJMgUYWEE1vMLy9tVqJHK6BcoszCwKSJ0xkL0');
define('OAUTH_TOKEN', '100175837-tiSERr5kns1C5QZrxN1iaZyH4VGtvEsbQGfPn5Bm');
define('OAUTH_TOKEN_SECRET', 'S2qRAOtmvIPrhHvstNYUl82cOClxcZyMRRHuoKplE');

?>

